[project]
channels = ["conda-forge"]
description = "Notebook for teaching machine learning concepts"
name = "learn-machine-learning-2025"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[dependencies]
numpy = "*"
pandas = "*"
matplotlib = "*"
seaborn = "*"
scikit-learn = "*"